In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
#Ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = '2020-2021.csv'
df = pd.read_csv(data)
df

Div        Date   Time          HomeTeam        AwayTeam  FTHG  FTAG FTR  \
0    E0  12/09/2020  12:30            Fulham         Arsenal     0     3   A   
1    E0  12/09/2020  15:00    Crystal Palace     Southampton     1     0   H   
2    E0  12/09/2020  17:30         Liverpool           Leeds     4     3   H   
3    E0  12/09/2020  20:00          West Ham       Newcastle     0     2   A   
4    E0  13/09/2020  14:00         West Brom       Leicester     0     3   A   
..   ..         ...    ...               ...             ...   ...   ...  ..   
375  E0  23/05/2021  16:00         Liverpool  Crystal Palace     2     0   H   
376  E0  23/05/2021  16:00          Man City         Everton     5     0   H   
377  E0  23/05/2021  16:00  Sheffield United         Burnley     1     0   H   
378  E0  23/05/2021  16:00          West Ham     Southampton     3     0   H   
379  E0  23/05/2021  16:00            Wolves      Man United     1     2   A   

     HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
0       0     1  ...     1.84  0.75      2.01      1.89   2.02   1.91   
1       1     0  ...     1.70  0.25      1.78      2.13   1.79   2.17   
2       3     2  ...     2.62 -1.50      1.85      2.05   1.85   2.08   
3       0     0  ...     1.92 -0.50      2.03      1.87   2.04   1.88   
4       0     0  ...     1.73  0.25      1.92      1.98   1.93   1.99   
..    ...   ...  ...      ...   ...       ...       ...    ...    ...   
375     1     0  ...     3.49 -2.25      1.86      2.04   1.88   2.03   
376     2     0  ...     2.77 -1.75      2.01      1.89   1.99   1.89   
377     1     0  ...     2.05  0.00      2.04      1.86   2.05   1.86   
378     2     0  ...     2.14 -0.75      2.00      1.90   2.02   1.91   
379     1     2  ...     1.62 -0.25      2.04      1.86   2.10   1.84   

     MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  
0       2.13     1.92     2.02     1.87  
1       1.85     2.18     1.79     2.12  
2       1.90     2.16     1.84     2.04  
3       2.09     1.91     2.02     1.86  
4       1.95     2.01     1.91     1.97  
..       ...      ...      ...      ...  
375     1.98     2.14     1.88     2.00  
376     2.20     2.00     2.03     1.85  
377     2.17     1.90     2.03     1.84  
378     2.06     2.01     1.99     1.89  
379     2.10     1.94     2.00     1.88  

[380 rows x 106 columns]

In [ ]:
import pandas as pd 
df.shape

(380, 106)

1) Complete Case Analysis(CCA):-

In [ ]:
# Step 01) Finding the columns that have Null Values(Missing Data): We are using a for loop for all the columns present in dataset with average null values greater than 0
na_variables = [ var for var in df.columns if df[var].isnull().mean() > 0 ]
na_variables

[]

In [ ]:

data_na = df[na_variables].isnull().mean()
data_na


Series([], dtype: float64)

In [ ]:
# Step 02) Implementing the CCA techniques to remove Missing Data
data_cca = df.dropna(axis=0)
df.shape,data_cca.shape

((380, 106), (380, 106))

2) Arbitrary Value Imputation:-

In [ ]:
#Using Arbitary Imputation technique, we will impute missing Edu with "Missing"  {You can use any other value also}
arb_impute = df['FTHG'].fillna('Missing')
arb_impute.unique()

array([0, 1, 4, 5, 2, 3, 7, 6, 9])

In [ ]:
missing_data=df.isnull().mean()
missing_data

Div         0.0
Date        0.0
Time        0.0
HomeTeam    0.0
AwayTeam    0.0
           ... 
PCAHA       0.0
MaxCAHH     0.0
MaxCAHA     0.0
AvgCAHH     0.0
AvgCAHA     0.0
Length: 106, dtype: float64

In [ ]:
 df['FTHG'].unique()

array([0, 1, 4, 5, 2, 3, 7, 6, 9])

3) Frequent Category Imputation:

In [ ]:
#Step 01) Finding the count of unique values in Edu
df['FTHG'].groupby(df['FTHG']).count()

FTHG
0    111
1    130
2     73
3     42
4     15
5      6
6      1
7      1
9      1
Name: FTHG, dtype: int64

In [ ]:

#Step 02) Finding the mode: 1 has higgest frequency. We can also do it by checking the mode
df['FTHG'].mode()

0    1
Name: FTHG, dtype: int64

In [ ]:
#Step 03) Using Frequent Category Imputer.
frq_impute =df['FTHG'].fillna('1')
frq_impute.unique()

array([0, 1, 4, 5, 2, 3, 7, 6, 9])